#pragma kernel Density
#include "./Includes/Density.compute"

float radius;

[numthreads(numThreads,numThreads,numThreads)]
void Density (int3 id : SV_DispatchThreadID)
{
    if (any(id >= dimensions))
        return;
    
    float3 pos = positionOfCoord(id);
    float density = clamp((1-length(pos - center)*2/boundsSize)*radius, 0.0, 1.0);

    int index = indexFromCoord(id);
    points[index] = lerp(densityRange.x, densityRange.y, density);
}
